CREATE TABLE IF NOT EXISTS edits (id TEXT PRIMARY KEY, op TEXT NOT NULL, data TEXT, ts INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS settings (k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attempts (ip TEXT NOT NULL, ts INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS attempts_ip ON attempts (ip, ts);
